[project]
name = "katas"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "pytest (>=8.3.4,<9.0.0)"
]

[tool.poetry]
packages = [
    { include = "src" },
]
